version: '3.9'

services:
  LukeTubeBackend:
    image: ${DOCKER_REGISTRY-}luketube
    build:
      context: .
      dockerfile: LukeTubeBackend.Dockerfile
    depends_on:
      - db
      - redis
#    restart: always
    restart: "no"
    expose:
      - "82"
    env_file:
      - ./.env
    ports:
      - 82:82

  angular:
    restart: always
    build:
      context: ./LukeTube/client
      dockerfile: Dockerfile
    depends_on:
      - LukeTubeBackend
    ports:
      - 81:80

  LukeTubeWorker:
    image: ${DOCKER_REGISTRY-}luketube-worker
    build:
      context: .
      dockerfile: LukeTubeWorker.Dockerfile
    restart: "no"
    depends_on:
      - db
    env_file:
      - ./.env

  db:
    image: postgres:14.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: SubredditDb
    restart: always
#    volumes:
#      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 6379:6379

  redis:
    image: redis:6.2.6
    restart: always

  jaeger:
    image: jaegertracing/all-in-one:latest
    volumes:
      - "./jaeger-ui.json:/etc/jaeger/jaeger-ui.json"
    command: --query.ui-config /etc/jaeger/jaeger-ui.json
    environment:
      - METRICS_STORAGE_TYPE=prometheus
      - PROMETHEUS_SERVER_URL=http://prometheus:9090
    ports:
#      - "14250:14250"
      - "14250"
      - "14268:14268"
      - "6831:6831/udp"
      - "16686:16686"
      - "16685:16685"

  otel_collector:
    image: otel/opentelemetry-collector-contrib:latest
    volumes:
      - "./otel-collector-config.yml:/etc/otelcol/otel-collector-config.yml"
    command: --config /etc/otelcol/otel-collector-config.yml
    ports:
      - "1888:1888" # pprof extention
      - "8888:8888" # prometheus metrics exposed by collector
      - "8889:8889" # prometheus exporter metrics
      - "13133:13133" # health check extensioh
      - "4317:4317" # otlp grpc receiver
      - "4318:4318" # otlp http receiver
      - "55679:55679" # zpages extension
    depends_on:
      - jaeger
      - prometheus

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"