version: '3.9'

services:
  LukeTubeBackend:
    image: ${DOCKER_REGISTRY-}luketube-backend
    build:
      context: .
      dockerfile: LukeTubeBackend.Dockerfile
    depends_on:
      - db
      - redis
    restart: "no"
    expose:
      - "82"
    env_file:
      - ./.env
    ports:
      - 82:82

  LukeTubeWorker:
    image: ${DOCKER_REGISTRY-}luketube-worker
    build:
      context: .
      dockerfile: LukeTubeWorker.Dockerfile
    restart: "no"
    depends_on:
      - db
    env_file:
      - ./.env

  db:
    image: postgres:14.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6
    restart: always