version: '3.9'

services:
  LukeTubeBackend:
    image: ${DOCKER_REGISTRY-}luketube-backend
    build:
      context: .
      dockerfile: LukeTubeBackend.Dockerfile
    depends_on:
      - db
      - redis
#    restart: always
    restart: "no"
    expose:
      - "82"
    #environment:
    #  WEB_PORTS: "80"
    #  VIRTUAL_HOST: "www.luketube.net"
    #  VIRTUAL_PATH: "/api/"
    #  VIRTUAL_DEST: "/"
    #   - CONNECTION_STRINGS__POSTGRESQL="host=db;database=SubredditDb;username=postgres;password=postgres"
    #  - CONNECTION_STRINGS__REDIS="redis,abortConnect=False"
    #  - LETSENCRYPT_HOST=luketube.net, www.luketube.net
    #  - VIRTUAL_HOST=luketube.net
    #  - VIRTUAL_PORT=80
    #  - ASPNETCORE_ENVIRONMENT=Development
    #  - ASPNETCORE_URLS=http://+:80
    env_file:
      - ./.env
    ports:
      - 82:82

  LukeTubeWorker:
    image: ${DOCKER_REGISTRY-}luketube-worker
    build:
      context: .
      dockerfile: LukeTubeWorker.Dockerfile
    restart: "no"
    depends_on:
      - db
    env_file:
      - ./.env

  db:
    image: postgres:14.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: SubredditDb
    restart: always
    ports:
      - 5432:5432
#    volumes:
#      - ./postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6
    restart: always

  #nginx-proxy:
  #  image: nginxproxy/nginx-proxy:1.0.0
  #  container_name: nginx-proxy
  #  restart: always
  #  volumes:
  #    - /var/run/docker.sock:/tmp/docker.sock:ro
  #    - ./.nginx/html/:/usr/share/nginx/html
  #    - ./.nginx/certs/:/etc/nginx/certs
  #    - ./.nginx/vhost/:/etc/nginx/vhost.d
  #  environment:
  #    - DEFAULT_HOST=luketube.local

  #  ports:
  #    - 80:80
  #    - 443:443
  #  depends_on:
  #    - LukeTube
  #    - angular
  #  labels:
  #    - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"

  #acme-companion:
  #  image: nginxproxy/acme-companion:2.1.2
  #  container_name: acme-companion
  #  restart: always
  #  volumes:
  #    - /var/run/docker.sock:/var/run/docker.sock:ro
  #    - ./.nginx/html/:/usr/share/nginx/html
  #    - ./.nginx/certs/:/etc/nginx/certs
  #    - ./.nginx/vhost/:/etc/nginx/vhost.d
  #    - ./.nginx/acme/:/etc/acme.sh
  #  env_file:
  #    - ./.env.acme-companion
  #  depends_on:
  #    - nginx-proxy